package com.example.webeid.controller;

import com.example.webeid.dto.ChallengeResponse;
import com.fasterxml.jackson.databind.ObjectMapper;
import eu.webeid.security.challenge.ChallengeNonce;
import eu.webeid.security.challenge.ChallengeNonceGenerator;
import eu.webeid.security.challenge.ChallengeNonceStore;
import org.bouncycastle.util.io.pem.PemObject;
import org.bouncycastle.util.io.pem.PemReader;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Profile;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContext;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.User;
import com.example.webeid.security.JwtService;
import org.springframework.web.bind.annotation.*;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.InputStreamReader;
import java.security.*;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.security.spec.PKCS8EncodedKeySpec;
import java.util.Base64;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Demo controller that simulates the smart card cryptographic operations on the backend.
 * This allows testing the full authentication flow without a physical eID card.
 *
 * Only loaded when the 'demo' Spring profile is active.
 * Will NOT be registered in production ('prod' profile).
 */
@Profile("demo")   // ← CRITICAL: never active in prod
@RestController
@RequestMapping("/api/auth/demo")
public class DemoAuthController {

    private final ChallengeNonceGenerator nonceGenerator;
    private final ChallengeNonceStore challengeNonceStore;
    private final JwtService jwtService;

    @Autowired
    public DemoAuthController(ChallengeNonceGenerator nonceGenerator, ChallengeNonceStore challengeNonceStore, JwtService jwtService) {
        this.nonceGenerator = nonceGenerator;
        this.challengeNonceStore = challengeNonceStore;
        this.jwtService = jwtService;
    }

    /**
     * Step 1: Get a challenge nonce (same as the real flow).
     */
    @GetMapping("/challenge")
    public ResponseEntity<ChallengeResponse> getDemoChallenge() {
        ChallengeNonce nonce = nonceGenerator.generateAndStoreNonce();
        return ResponseEntity.ok(new ChallengeResponse(nonce.getBase64EncodedNonce()));
    }

    /**
     * Step 2: Simulates what the smart card does – signs the nonce using the test private key.
     * Normally this happens inside the secure hardware of the eID card, PIN-protected.
     * 
     * Here, the backend does it server-side for demo/testing purposes ONLY.
     */

    @PostMapping("/login")
    public ResponseEntity<?> demoLogin(HttpServletRequest request, HttpServletResponse response) {
        try {
            // 1. Get the stored nonce (it was generated by /api/auth/demo/challenge)
            ChallengeNonce storedNonce = challengeNonceStore.getAndRemove();
            if (storedNonce == null) {
                return ResponseEntity.status(400).body(
                    Map.of("error", "No challenge nonce found. Call /api/auth/demo/challenge first.")
                );
            }
            String nonce = storedNonce.getBase64EncodedNonce();

            // 2. Load the test certificate
            X509Certificate cert = loadTestCertificate();
            String certBase64 = Base64.getEncoder().encodeToString(cert.getEncoded());

            // 3. Load the test private key and sign the nonce (simulating the smart card)
            PrivateKey privateKey = loadTestPrivateKey();
            byte[] signatureBytes = signWithRsaSha256(nonce.getBytes(), privateKey);
            String signatureBase64 = Base64.getEncoder().encodeToString(signatureBytes);

            // 4. Build a fake Web eID auth token JSON (the format the real extension sends)
            // The real token format from the web-eid-library:
            // { "unverifiedCertificate": "<base64 cert>", "algorithm": "RS256",
            //   "signature": "<base64 sig>", "format": "web-eid:1", "appVersion": "..." }
            Map<String, Object> tokenMap = new LinkedHashMap<>();
            tokenMap.put("unverifiedCertificate", certBase64);
            tokenMap.put("algorithm", "RS256");
            tokenMap.put("signature", signatureBase64);
            tokenMap.put("format", "web-eid:1");
            tokenMap.put("appVersion", "https://web-eid.eu/web-eid-app/releases/v2.5.0");

            String tokenJson = new ObjectMapper().writeValueAsString(tokenMap);

            // 5. Log in user directly (bypass the AuthTokenValidator since it needs strict PKI)
            //    In a real scenario, the token goes to /api/auth/login where AuthTokenValidator checks it.
            //    For the demo, we trust our own self-signed cert directly.
            String subjectDn = cert.getSubjectX500Principal().getName();
            String displayName = extractCN(subjectDn);

            // Generate JWT token
            List<String> roles = List.of("ROLE_USER");
            String jwtToken = jwtService.generateToken(displayName, roles);

            return ResponseEntity.ok(Map.of(
                "status", "AUTHENTICATED",
                "user", displayName,
                "subjectDn", subjectDn,
                "certificateInfo", Map.of(
                    "subject", subjectDn,
                    "issuer", cert.getIssuerX500Principal().getName(),
                    "validFrom", cert.getNotBefore().toString(),
                    "validUntil", cert.getNotAfter().toString(),
                    "serialNumber", cert.getSerialNumber().toString()
                ),
                "simulatedToken", tokenJson,
                "token", jwtToken
            ));

        } catch (Exception e) {
            e.printStackTrace();
            return ResponseEntity.status(500).body(Map.of("error", "Demo login failed: " + e.getMessage()));
        }
    }

    private X509Certificate loadTestCertificate() throws Exception {
        CertificateFactory cf = CertificateFactory.getInstance("X.509");
        return (X509Certificate) cf.generateCertificate(
            new ClassPathResource("certs/test-cert.pem").getInputStream()
        );
    }

    private PrivateKey loadTestPrivateKey() throws Exception {
        try (PemReader pemReader = new PemReader(
                new InputStreamReader(new ClassPathResource("certs/test-key.pem").getInputStream()))) {
            PemObject pemObject = pemReader.readPemObject();
            PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(pemObject.getContent());
            KeyFactory keyFactory = KeyFactory.getInstance("RSA");
            return keyFactory.generatePrivate(keySpec);
        }
    }

    private byte[] signWithRsaSha256(byte[] data, PrivateKey privateKey) throws Exception {
        Signature signature = Signature.getInstance("SHA256withRSA");
        signature.initSign(privateKey);
        signature.update(data);
        return signature.sign();
    }

    private String extractCN(String subjectDn) {
        // Parse CN= from the DN string (format: CN=Name,O=Org,C=EE)
        for (String part : subjectDn.split(",")) {
            String trimmed = part.trim();
            if (trimmed.startsWith("CN=")) {
                return trimmed.substring(3);
            }
        }
        return subjectDn;
    }
}
